__Identifier:
    refresh: refresh rate in seconds
    tracked:
        - list
        - of
        - epics

NixonInnesDemo:
    refresh: 5
    tracked:
        - CS.D.BITCOIN.CFD.IP
        - CS.D.ETHUSD.CFD.IP
